
ALTER TABLE pokemon ALTER COLUMN base_experience DROP NOT NULL;
ALTER TABLE pokemon ALTER COLUMN name DROP NOT NULL;

ALTER TABLE pokemon ALTER COLUMN pokemon_id DROP NOT NULL;
ALTER TABLE pokemon ALTER COLUMN name DROP NOT NULL;

