package com.pokeapi.backend.dto;

import java.util.Map;

/**
 * 월드컵 생성 요청용 DTO
 * 클라이언트에서 월드컵 생성 요청을 받을 때 사용
 */
public class WorldCupRequestDTO {
    
    private String title;                    // 월드컵 제목
    private String tournamentType = "vote";  // 토너먼트 타입 (기본값: vote)
    
    // 조건 설정
    private Integer participantCount = 16;   // 참가자 수 (기본값: 16)
    private String generation;               // 세대 (예: "1", "2", "all")
    private String type;                     // 타입 (예: "불꽃", "물", "all")
    
    // 추가 조건 (선택사항)
    private Map<String, Object> additionalConditions;
    
    // 자동 생성 여부
    private Boolean isAutoGenerated = false; // 자동 생성 여부

    // Getters and Setters
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTournamentType() {
        return tournamentType;
    }

    public void setTournamentType(String tournamentType) {
        this.tournamentType = tournamentType;
    }

    public Integer getParticipantCount() {
        return participantCount;
    }

    public void setParticipantCount(Integer participantCount) {
        this.participantCount = participantCount;
    }

    public String getGeneration() {
        return generation;
    }

    public void setGeneration(String generation) {
        this.generation = generation;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Map<String, Object> getAdditionalConditions() {
        return additionalConditions;
    }

    public void setAdditionalConditions(Map<String, Object> additionalConditions) {
        this.additionalConditions = additionalConditions;
    }

    public Boolean getIsAutoGenerated() {
        return isAutoGenerated;
    }

    public void setIsAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
    }
} 