package com.pokeapi.backend.dto;

import lombok.Data;

import java.util.Map;

/**
 * 월드컵 생성 요청용 DTO
 * 클라이언트에서 월드컵 생성 요청을 받을 때 사용
 */
@Data
public class WorldCupRequestDTO {
    
    private String title;                    // 월드컵 제목
    private String tournamentType = "vote";  // 토너먼트 타입 (기본값: vote)
    
    // 조건 설정
    private Integer participantCount = 16;   // 참가자 수 (기본값: 16)
    private String generation;               // 세대 (예: "1", "2", "all")
    private String type;                     // 타입 (예: "불꽃", "물", "all")
    
    // 추가 조건 (선택사항)
    private Map<String, Object> additionalConditions;
    
    // 자동 생성 여부
    private Boolean isAutoGenerated = false; // 자동 생성 여부
} 